name: Create Alfred Workflow
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - name: Create Alfred workflow package
      id: alfred_builder
      run: |
        rm -f caniuse.alfredworkflow
        zip -j -D caniuse.alfredworkflow info.plist
        zip -j -D caniuse.alfredworkflow target/release/caniuse
        zip -j -D caniuse.alfredworkflow README.md
        zip -j -D caniuse.alfredworkflow LICENSE
        echo "::set-output name=workflow_file::caniuse.alfredworkflow"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: "${{ github.ref }}-alfredworkflow"
        draft: false
        prerelease: false
    - name: Upload Alfred Workflow
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.alfred_builder.outputs.workflow_file }}
        asset_name: ${{ steps.alfred_builder.outputs.workflow_file }}
        asset_content_type: application/zip
