name: Release to crates.io and GitHub Releases
on:
  push:
    tags:
      - 'v*'

jobs:
  lint_with_clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: clippy

  build_linux:
    runs-on: ubuntu-latest
    outputs: # map step output to job output for use in the GitHub Release job
      caniuse-linux-x86: ${{ steps.build_linux.outputs.caniuse-linux-x86 }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Targets
        run: make install-targets-linux
      - name: Build Linux
        id: build_linux
        run: |
          make build-linux
          echo "::set-output name=caniuse-linux-x86::target/x86_64-unknown-linux-gnu/release/caniuse"

  build_mac_x86:
    runs-on: macos-11
    outputs: # map step output to job output for use in the GitHub Release job
      caniuse-macos-x86: ${{ steps.build_mac_x86.outputs.caniuse-macos-x86 }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Targets
        run: make install-targets-mac-x86
      - name: Build MacOS
        id: build_mac_x86
        run: |
          make build-macos-x86
          echo "::set-output name=caniuse-macos-x86::target/x86_64-apple-darwin/release/caniuse"

  build_mac_arm:
    runs-on: macos-11
    outputs: # map step output to job output for use in the GitHub Release job
      caniuse-macos-arm: ${{ steps.build_mac_arm.outputs.caniuse-macos-arm }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Targets
        run: make install-targets-mac-arm
      - name: Build MacOS
        id: build_mac_arm
        run: |
          make build-macos-arm
          echo "::set-output name=caniuse-macos-arm::target/aarch64-apple-darwin/release/caniuse"

  build_alfred_workflows:
    runs-on: macos-11
    needs: [build_mac_x86, build_mac_arm]
    outputs: # map step output to job output for use in the GitHub Release job
      alfred_workflow_file: ${{ steps.build_alfred_workflows.outputs.alfred_workflow_file }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Create Alfred Workflow File
        id: build_alfred_workflows
        run: |
          make alfred-workflow-x86
          make alfred-workflow-arm
          echo "::set-output name=alfred_workflow_file_x86::caniuse-x86.alfredworkflow"
          echo "::set-output name=alfred_workflow_file_arm::caniuse-arm.alfredworkflow"

  create_github_release:
    runs-on: ubuntu-latest
    needs: [build_linux, build_mac_x86, build_mac_arm, build_alfred_workflows]
    steps:
      - uses: actions/checkout@v2
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            ${{ needs.build_mac_x86.outputs.caniuse-macos-x86 }}
            ${{ needs.build_mac_arm.outputs.caniuse-macos-arm }}
            ${{ needs.build_linux.outputs.caniuse-linux-x86 }}
            ${{ needs.build_alfred_workflows.outputs.alfred_workflow_file_x86 }}
            ${{ needs.build_alfred_workflows.outputs.alfred_workflow_file_arm }}

  cargo_publish:
    runs-on: ubuntu-latest
    needs: create_github_release
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cargo Publish
        env:
          CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
        run: make publish
