name: Release to crates.io and GitHub Releases
on:
  push:
    tags:
      - 'v*'

jobs:
  lint-with-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: clippy

  build-linux:
    runs-on: ubuntu-latest
    needs: lint-with-clippy
    outputs: # map step output to job output for use in the GitHub Release job
      caniuse-linux-x86: ${{ steps.build-linux.outputs.caniuse-linux-x86 }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Targets
        run: make install-targets-linux
      - name: Build Linux
        id: build-linux
        run: |
          make build-linux
          echo "::set-output name=caniuse-linux-x86::target/x86_64-unknown-linux-gnu/release/caniuse"

  build-mac-x86:
    runs-on: macos-11
    needs: lint-with-clippy
    outputs: # map step output to job output for use in the GitHub Release job
      caniuse-macos-x86: ${{ steps.build-mac-x86.outputs.caniuse-macos-x86 }}
      alfred-workflow-x86: ${{ steps.alfred-workflow-x86.outputs.alfred-workflow-x86 }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Targets
        run: make install-targets-mac-x86
      - name: Build MacOS x86
        id: build-mac-x86
        run: |
          make build-macos-x86
          echo "::set-output name=caniuse-macos-x86::target/x86_64-apple-darwin/release/caniuse"
      - name: Build x86 Alfred Workflow
        id: alfred-workflow-x86
        run: |
          make WORKFLOW_FILE_NAME="caniuse-x86.alfredworkflow" CANIUSE_BIN="target/x86_64-apple-darwin/release/caniuse" alfred-workflow
          echo "::set-output name=alfred-workflow-x86::caniuse-x86.alfredworkflow"


  build-mac-arm:
    runs-on: macos-11
    needs: lint-with-clippy
    outputs: # map step output to job output for use in the GitHub Release job
      caniuse-macos-arm: ${{ steps.build-mac-arm.outputs.caniuse-macos-arm }}
      alfred_workflow_file_arm: ${{ steps.alfred-workflow-arm.outputs.alfred-workflow-arm }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Targets
        run: make install-targets-mac-arm
      - name: Build MacOS ARM
        id: build-mac-arm
        run: |
          make build-macos-arm
          echo "::set-output name=caniuse-macos-arm::target/aarch64-apple-darwin/release/caniuse"
      - name: Build x86 Alfred Workflow
        id: alfred-workflow-arm
        run: |
          make WORKFLOW_FILE_NAME="caniuse-arm.alfredworkflow" CANIUSE_BIN="target/aarch64-apple-darwin/release/caniuse" alfred-workflow
          echo "::set-output name=alfred-workflow-arm::caniuse-arm.alfredworkflow"

  create-github-release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-mac-x86, build-mac-arm]
    steps:
      - uses: actions/checkout@v2
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            ${{ needs.build-mac-x86.outputs.caniuse-macos-x86 }}
            ${{ needs.build-mac-x86.outputs.alfred-workflow-x86 }}
            ${{ needs.build-mac-arm.outputs.caniuse-macos-arm }}
            ${{ needs.build-mac-arm.outputs.alfred-workflow-arm }}
            ${{ needs.build-linux.outputs.caniuse-linux-x86 }}

  cargo-publish:
    runs-on: ubuntu-latest
    needs: create-github-release
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cargo Publish
        env:
          CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
        run: make publish
